# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95ea845cf936d0ba7d77d062a20426bdbfd329aa3b5fd4d42871d6fc751ca36ff9855344c3635952d49097bf37ac6d6151069299b0a7bf1a228e5ea0b6d8b44
  google_calendar_reservation_cal: 7niit4bglqaq74la04jee8ddc4@group.calendar.google.com
  google_calendar_project_publishing_cal: knk6vm0gs72glbt1smh03t0pp0@group.calendar.google.com

test:
  secret_key_base: fcadf6b097347a33be6e0b3342aef28a6dc57ad8d7dc64bf85128ff878cfdbbbaf98616a126c2f8a0b505026657b9a284ddca6001945b5decff9ce01f0d226d1

# Do not keep production secrets in the repository, read values from the
# environment instead.
production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  google_application_credentials: <%= Figaro.env.google_application_credentials %>
  google_calendar_reservation_cal: <%= Figaro.env.google_calendar_reservation_cal_id %>
  google_calendar_project_publishing_cal: <%= Figaro.env.google_calendar_project_publishing_cal_id %>
