# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: string_base_64
  google_calendar_reservation_cal: calendar_id@group.calendar.google.com
  google_calendar_project_publishing_cal: calendar_id@group.calendar.google.com
  google_calendar_vidcam_cal: calendar_id@group.calendar.google.com
  asana_personal_access_token: string_token
  asana_lrc_workspace_id: numeric_id
  asana_lrcerebro_project_id: numeric_id
  asana_lrcerebro_tag_task_id: numeric_id

test:
  secret_key_base: string_base_64

# Do not keep production secrets in the repository, read values from the
# environment instead.
production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
  google_application_credentials: <%= Figaro.env.google_application_credentials %>
  google_calendar_reservation_cal: <%= Figaro.env.google_calendar_reservation_cal_id %>
  google_calendar_project_publishing_cal: <%= Figaro.env.google_calendar_project_publishing_cal_id %>
  google_calendar_vidcam_cal: <%= Figaro.env.google_calendar_vidcam_cal_id %>
  asana_personal_access_token: <%= Figaro.env.asana_personal_access_token %>
  asana_lrc_workspace_id: <%= Figaro.env.asana_lrc_workspace_id %>
  asana_lrcerebro_project_id: <%= Figaro.env.asana_lrcerebro_project_id %>
  asana_lrcerebro_tag_task_id: <%= Figaro.env.asana_lrcerebro_tag_task_id %>
